export const portfolioConfig = {
  name: "Danica Bautista",
  eyebrow: "Business Management · Data foundations · Student leadership",
  headline: "A considered start to meaningful work.",
  introduction: "I am a Business Management undergraduate who enjoys turning curiosity into practical contribution. My early experience combines data foundations, market research, student leadership, process simulation, and collaborative consultancy work.",
  availability: "Seeking graduate opportunities.",
  email: "bdanica538@gmail.com",
  phone: "+44 7415 367 484",
  location: "United Kingdom",
  stylePreset: "aqua",
  skills: ["Excel-based analysis & simulation", "Data & SQL foundations", "Market research & insight", "Commercial awareness", "Stakeholder communication", "Team leadership & organisation"],
  education: [
    { title: "BA Business Management with Placement Year", meta: "University of Sheffield · September 2024–present", body: "First-year weighted average of 84.8%, with First-Class Honours predicted. Relevant study includes Business Intelligence and Analysis for Decision-Making, using Qlik and Excel-based data analysis." },
    { title: "International Baccalaureate Diploma Programme", meta: "Brent International School Manila · August 2022–May 2024", body: "Final score of 34 points, with Higher Level subjects recorded as equivalent to AAB at A levels." },
  ],
  experience: [
    { title: "Spring Internship Experience", meta: "University of Sheffield · 13–17 April 2026", body: "Worked in a multidisciplinary team on a consultancy project set by OCU Group, developing research, critical-thinking, interpersonal, and knowledge-application skills." },
    { title: "Human Resources Director", meta: "Enactus Sheffield · October 2025–July 2026", body: "Supports the student-led social enterprise through member onboarding, internal documentation, recruitment reporting, and practical use of spreadsheets to monitor progress." },
    { title: "Faculty & Academic (Course) Representative", meta: "University of Sheffield · November 2024–present", body: "Gathers student feedback, supports staff–student communication, and contributes to inclusive faculty-level improvement through structured stakeholder updates." },
    { title: "Student Observation of Teaching", meta: "University of Sheffield · 2025/2026", body: "Participated in the Student Observation of Teaching programme, engaging thoughtfully with learning and reflective academic practice." },
  ],
  achievements: [
    { title: "Education Awards 2025/26", meta: "University of Sheffield · Student contribution to Education", body: "Recognised through a nomination for student contribution to education, reflecting feedback gathering, staff–student communication, peer advocacy, and positive faculty-level change." },
    { title: "Student Staff Partnership Award", meta: "Sheffield Students’ Union · Academic Reps", body: "Received the Student Staff Partnership Award, recognising constructive partnership and contribution within the student academic-representation community." },
    { title: "Universities Business Challenge", meta: "November 2025 – Feb 2026 · Round 1 & Round 2 (Semi-finals)", body: "Led a team representing the University of Sheffield, completing Round 1 and progressing to Round 2 (Semi-finals) of this business simulation focused on analytical thinking, commercial awareness, planning, and teamwork." },
    { title: "Introduction to Data and SQL", meta: "Code First Girls · October 2025", body: "Completed introductory training in data and SQL, building a sound foundation for working confidently with structured information." },
  ],
  projects: [
    { title: "Graduate benefits market research", date: "April 2026", meta: "OCU Group consultancy · Spring Internship Experience", body: "Co-created a market-research dataset, benchmarked 26 companies, and contributed to a student survey of 51 respondents to assess how early-career benefits are communicated.", supportingDocument: null },
    { title: "Benefits benchmarking model", date: "April 2026", meta: "OCU Group consultancy · Data visualisation", body: "Contributed to a structured scoring model covering financial support, lifestyle, career development, security, and transparency to make graduate-package comparisons clearer.", supportingDocument: null },
    { title: "Operations process-improvement simulation", date: "April 2026", meta: "MGT253 · University of Sheffield", body: "Used Microsoft Excel simulations to map work-in-progress, test throughput and capacity scenarios, identify process bottlenecks, and develop evidence-based improvement recommendations.", supportingDocument: null },
    { title: "International HRM strategy analysis", date: "May 2026", meta: "MGT226 · University of Sheffield", body: "Evaluated standardisation, localisation, and hybridisation approaches to international HRM, using academic frameworks and case evidence to assess global and local decision-making.", supportingDocument: null },
    { title: "Consumer & market analysis", date: "May 2026", meta: "MGT233 · University of Sheffield", body: "Produced an in-depth marketing analysis of Buldak pouch noodles in the US market, examining competition, consumer behaviour, marketing mix, segmentation, targeting, positioning, and digital promotion.", supportingDocument: null },
    { title: "BA Better World Collab campaign pitch", date: "July 2026", meta: "Mock campaign pitch · Internship Experience UK with British Airways", body: "Created a BA Better World Collab campaign pitch around creator partnership, digital content, social media, process planning, and measurable engagement goals for inclusion and self-expression.", supportingDocument: null },
    { title: "Business simulation challenge", date: "November 2025 – Feb 2026", meta: "Universities Business Challenge · Round 1 & Round 2 (Semi-finals)", body: "Led a team representing the University of Sheffield, completing Round 1 and progressing to Round 2 (Semi-finals) of a competitive business simulation that developed structured commercial decision-making and team-based planning.", supportingDocument: null },
  ],
  creativeWork: [
    { title: "The Watchdog — Student News Visual Identity", meta: "Logo draft · Brent International School, Baguio, Philippines", body: "Created an original student-newspaper logo draft that combines a bold wordmark with a custom watchdog mascot treatment.", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663730720797/QUOtXqCLDRBVtsmF.png", alt: "The Watchdog student-news visual identity logo draft with an illustrated watchdog mascot" },
    { title: "IB art exhibition render", meta: "International Baccalaureate Artworks · Brent International School, Baguio, Philippines", body: "Produced a virtual-gallery render presenting a curated collection of original artworks as a coherent exhibition environment.", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663730720797/OkDIexPyVnQPfjhz.png", alt: "Virtual-gallery render showing a curated International Baccalaureate art exhibition by a Brent International School student" },
  ],
  certificates: [
    { title: "Universities Business Challenge", detail: "Round 1 certificate · November 2025 – Feb 2026", issuer: "Universities Business Challenge Worldwide", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663730720797/XnxITCrFmjwdufIt.png", alt: "Universities Business Challenge Round 1 certificate awarded to Danica Bautista" },
    { title: "Introduction to Data and SQL", detail: "Completed · October 2025", issuer: "Code First Girls", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663730720797/QSyJrglyBSVvqkgZ.png", alt: "Code First Girls Introduction to Data and SQL certificate awarded to Danica Bautista" },
    { title: "Student Observation of Teaching", detail: "Participant · 2025/2026", issuer: "University of Sheffield", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663730720797/WYBoDAGxsBUDMwRE.png", alt: "University of Sheffield Student Observation of Teaching certificate for Danica Bautista" },
    { title: "Spring Internship Experience", detail: "13–17 April 2026", issuer: "University of Sheffield", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663730720797/aUtlzSqdGIFrUrUS.png", alt: "University of Sheffield Spring Internship Experience certificate for Danica Bautista" },
    { title: "Education Awards 2025/26", detail: "Student contribution to Education", issuer: "University of Sheffield", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663730720797/sMCjJdrpgxxysTHA.png", alt: "University of Sheffield Education Awards 2025/26 certificate recognising Danica Bautista's nomination for student contribution to education" },
    { title: "Student Staff Partnership Award", detail: "Academic Reps recognition · award photograph", issuer: "Sheffield Students’ Union", image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663730720797/LdCMGAttzNgFqAVQ.png", alt: "Cleaned scanned-style award photograph of the Student Staff Partnership Award presented to Danica Bautista by Sheffield Students' Union Academic Reps" },
  ],
} as const;
